Fix: nanopb_generator.py relative import issue
This change extends the PYTHON_PATH variable with the location of the
nanopb python directory to fix stability issues when nanopb generation
step is executed.

Sometimes due to unknown circumstances, execution of nanopb_generator.py
fails and the following import error is reported:
  "....
  from .proto import nanopb_pb2
  ImportError: attempted relative import with no known parent package"

Some systems never encounter this problem, while others fail randomly.

Change-Id: Idad916e30b6963369445f25085033ba035a39eca
Signed-off-by: Gyorgy Szing <Gyorgy.Szing@arm.com>